# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tfgg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/cpuclk
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/Controller_ROM
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/DRAM2
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/DRAM3
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/IROM
    d:/lab2_miniRV/proj_single_cycle.gen/sources_1/ip/DRAM1
    d:/lab2_miniRV/proj_single_cycle.gen/sources_1/ip/DRAM0
  } C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include {
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/cpuclk
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/Controller_ROM
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/DRAM2
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/DRAM3
    D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/ip/IROM
    d:/lab2_miniRV/proj_single_cycle.gen/sources_1/ip/DRAM1
    d:/lab2_miniRV/proj_single_cycle.gen/sources_1/ip/DRAM0
  } {
      D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/DRAM1_stub.v
      D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/DRAM0_stub.v
      D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/cpuclk_stub.v
      D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/Controller_ROM_stub.v
      D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/DRAM2_stub.v
      D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/DRAM3_stub.v
      D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/realtime/IROM_stub.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/defines.vh
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/ALU.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/Bridge.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/Controller.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/DM.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/LED.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/MaskedDRAM.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/NPC.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/PC.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/RF.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/SEXT.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/Switches.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/dig_controller.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/myCPU.v
      D:/lab2_miniRV/proj_single_cycle.srcs/sources_1/new/miniRV_SoC.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top miniRV_SoC
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/lab2_miniRV/.Xil/Vivado-11592-Mech-Win-Tera/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
